name: CI

on: [ push , pull_request ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ '7.4', '8.2' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: 'xdebug'

      - name: Update composer dependencies
        run: composer update --no-interaction --no-progress

      - name: Run tests and collect coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml .

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true